//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference4
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
    public partial class JghFault : object
    {
        
        private string NarrativeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Narrative
        {
            get
            {
                return this.NarrativeField;
            }
            set
            {
                this.NarrativeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:wsdlnamespace.RezultzSvc.WebApp01", ConfigurationName="ServiceReference4.ITimeKeepingSvc")]
    public interface ITimeKeepingSvc
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetIfServiceIsAnswering", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetIfServiceIsAnsweringResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference4.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetIfServiceIsAnsweringJghF" +
            "aultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<bool> GetIfServiceIsAnsweringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetServiceEndpointsInfo", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetServiceEndpointsInfoResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference4.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetServiceEndpointsInfoJghF" +
            "aultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string[]> GetServiceEndpointsInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetIfContainerExists", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetIfContainerExistsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference4.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetIfContainerExistsJghFaul" +
            "tFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<bool> GetIfContainerExistsAsync(string databaseAccount, string dataContainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/PostTimeStampItem", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/PostTimeStampItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference4.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/PostTimeStampItemJghFaultFa" +
            "ult", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string> PostTimeStampItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey, string clockItemAsJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/PostTimeStampItemArray", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/PostTimeStampItemArrayRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference4.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/PostTimeStampItemArrayJghFa" +
            "ultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string> PostTimeStampItemArrayAsync(string databaseAccount, string dataContainer, byte[] itemArrayAsJsonAsCompressedBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetTimeStampItem", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetTimeStampItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference4.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetTimeStampItemJghFaultFau" +
            "lt", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string> GetTimeStampItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetTimeStampItemArray", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetTimeStampItemArrayRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference4.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/ITimeKeepingSvc/GetTimeStampItemArrayJghFau" +
            "ltFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<byte[]> GetTimeStampItemArrayAsync(string databaseAccount, string dataContainer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ITimeKeepingSvcChannel : ServiceReference4.ITimeKeepingSvc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class TimeKeepingSvcClient : System.ServiceModel.ClientBase<ServiceReference4.ITimeKeepingSvc>, ServiceReference4.ITimeKeepingSvc
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TimeKeepingSvcClient(EndpointConfiguration endpointConfiguration) : 
                base(TimeKeepingSvcClient.GetBindingForEndpoint(endpointConfiguration), TimeKeepingSvcClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimeKeepingSvcClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TimeKeepingSvcClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimeKeepingSvcClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TimeKeepingSvcClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimeKeepingSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> GetIfServiceIsAnsweringAsync()
        {
            return base.Channel.GetIfServiceIsAnsweringAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetServiceEndpointsInfoAsync()
        {
            return base.Channel.GetServiceEndpointsInfoAsync();
        }
        
        public System.Threading.Tasks.Task<bool> GetIfContainerExistsAsync(string databaseAccount, string dataContainer)
        {
            return base.Channel.GetIfContainerExistsAsync(databaseAccount, dataContainer);
        }
        
        public System.Threading.Tasks.Task<string> PostTimeStampItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey, string clockItemAsJson)
        {
            return base.Channel.PostTimeStampItemAsync(databaseAccount, dataContainer, tablePartition, tableRowKey, clockItemAsJson);
        }
        
        public System.Threading.Tasks.Task<string> PostTimeStampItemArrayAsync(string databaseAccount, string dataContainer, byte[] itemArrayAsJsonAsCompressedBytes)
        {
            return base.Channel.PostTimeStampItemArrayAsync(databaseAccount, dataContainer, itemArrayAsJsonAsCompressedBytes);
        }
        
        public System.Threading.Tasks.Task<string> GetTimeStampItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey)
        {
            return base.Channel.GetTimeStampItemAsync(databaseAccount, dataContainer, tablePartition, tableRowKey);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetTimeStampItemArrayAsync(string databaseAccount, string dataContainer)
        {
            return base.Channel.GetTimeStampItemArrayAsync(databaseAccount, dataContainer);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyHttpTextBinding_ITimeKeepingSvc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsTextBinding_ITimeKeepingSvc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsCustomBinaryBinding_ITimeKeepingSvc))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyHttpTextBinding_ITimeKeepingSvc))
            {
                return new System.ServiceModel.EndpointAddress("http://rezultzsvccorewcf.azurewebsites.net/ITimeKeepingSvc/HttpText");
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsTextBinding_ITimeKeepingSvc))
            {
                return new System.ServiceModel.EndpointAddress("https://rezultzsvccorewcf.azurewebsites.net/ITimeKeepingSvc/HttpsText");
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsCustomBinaryBinding_ITimeKeepingSvc))
            {
                return new System.ServiceModel.EndpointAddress("https://rezultzsvccorewcf.azurewebsites.net/ITimeKeepingSvc/HttpsBinary");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MyHttpTextBinding_ITimeKeepingSvc,
            
            MyHttpsTextBinding_ITimeKeepingSvc,
            
            MyHttpsCustomBinaryBinding_ITimeKeepingSvc,
        }
    }
}
