//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
    public partial class JghFault : object
    {
        
        private string NarrativeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Narrative
        {
            get
            {
                return this.NarrativeField;
            }
            set
            {
                this.NarrativeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:wsdlnamespace.RezultzSvc.WebApp01", ConfigurationName="ServiceReference2.IParticipantRegistrationSvc")]
    public interface IParticipantRegistrationSvc
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetIfServiceIsA" +
            "nswering", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetIfServiceIsA" +
            "nsweringResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetIfServiceIsA" +
            "nsweringJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<bool> GetIfServiceIsAnsweringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetServiceEndpo" +
            "intsInfo", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetServiceEndpo" +
            "intsInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetServiceEndpo" +
            "intsInfoJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string[]> GetServiceEndpointsInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetIfContainerE" +
            "xists", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetIfContainerE" +
            "xistsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetIfContainerE" +
            "xistsJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<bool> GetIfContainerExistsAsync(string databaseAccount, string dataContainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/PostParticipant" +
            "Item", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/PostParticipant" +
            "ItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/PostParticipant" +
            "ItemJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string> PostParticipantItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey, string participantItemAsJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/PostParticipant" +
            "ItemArray", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/PostParticipant" +
            "ItemArrayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/PostParticipant" +
            "ItemArrayJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string> PostParticipantItemArrayAsync(string databaseAccount, string dataContainer, byte[] itemArrayAsJsonAsCompressedBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetParticipantI" +
            "tem", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetParticipantI" +
            "temResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetParticipantI" +
            "temJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<string> GetParticipantItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetParticipantI" +
            "temArray", ReplyAction="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetParticipantI" +
            "temArrayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.JghFault), Action="urn:wsdlnamespace.RezultzSvc.WebApp01/IParticipantRegistrationSvc/GetParticipantI" +
            "temArrayJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.WebApp01")]
        System.Threading.Tasks.Task<byte[]> GetParticipantItemArrayAsync(string databaseAccount, string dataContainer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IParticipantRegistrationSvcChannel : ServiceReference2.IParticipantRegistrationSvc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ParticipantRegistrationSvcClient : System.ServiceModel.ClientBase<ServiceReference2.IParticipantRegistrationSvc>, ServiceReference2.IParticipantRegistrationSvc
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ParticipantRegistrationSvcClient(EndpointConfiguration endpointConfiguration) : 
                base(ParticipantRegistrationSvcClient.GetBindingForEndpoint(endpointConfiguration), ParticipantRegistrationSvcClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParticipantRegistrationSvcClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ParticipantRegistrationSvcClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParticipantRegistrationSvcClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ParticipantRegistrationSvcClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParticipantRegistrationSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> GetIfServiceIsAnsweringAsync()
        {
            return base.Channel.GetIfServiceIsAnsweringAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetServiceEndpointsInfoAsync()
        {
            return base.Channel.GetServiceEndpointsInfoAsync();
        }
        
        public System.Threading.Tasks.Task<bool> GetIfContainerExistsAsync(string databaseAccount, string dataContainer)
        {
            return base.Channel.GetIfContainerExistsAsync(databaseAccount, dataContainer);
        }
        
        public System.Threading.Tasks.Task<string> PostParticipantItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey, string participantItemAsJson)
        {
            return base.Channel.PostParticipantItemAsync(databaseAccount, dataContainer, tablePartition, tableRowKey, participantItemAsJson);
        }
        
        public System.Threading.Tasks.Task<string> PostParticipantItemArrayAsync(string databaseAccount, string dataContainer, byte[] itemArrayAsJsonAsCompressedBytes)
        {
            return base.Channel.PostParticipantItemArrayAsync(databaseAccount, dataContainer, itemArrayAsJsonAsCompressedBytes);
        }
        
        public System.Threading.Tasks.Task<string> GetParticipantItemAsync(string databaseAccount, string dataContainer, string tablePartition, string tableRowKey)
        {
            return base.Channel.GetParticipantItemAsync(databaseAccount, dataContainer, tablePartition, tableRowKey);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetParticipantItemArrayAsync(string databaseAccount, string dataContainer)
        {
            return base.Channel.GetParticipantItemArrayAsync(databaseAccount, dataContainer);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyHttpTextBinding_IParticipantRegistrationSvc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsTextBinding_IParticipantRegistrationSvc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsCustomBinaryBinding_IParticipantRegistrationSvc))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyHttpTextBinding_IParticipantRegistrationSvc))
            {
                return new System.ServiceModel.EndpointAddress("http://rezultzsvccorewcf.azurewebsites.net/IParticipantRegistrationSvc/HttpText");
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsTextBinding_IParticipantRegistrationSvc))
            {
                return new System.ServiceModel.EndpointAddress("https://rezultzsvccorewcf.azurewebsites.net/IParticipantRegistrationSvc/HttpsText" +
                        "");
            }
            if ((endpointConfiguration == EndpointConfiguration.MyHttpsCustomBinaryBinding_IParticipantRegistrationSvc))
            {
                return new System.ServiceModel.EndpointAddress("https://rezultzsvccorewcf.azurewebsites.net/IParticipantRegistrationSvc/HttpsBina" +
                        "ry");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MyHttpTextBinding_IParticipantRegistrationSvc,
            
            MyHttpsTextBinding_IParticipantRegistrationSvc,
            
            MyHttpsCustomBinaryBinding_IParticipantRegistrationSvc,
        }
    }
}
