//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultz.Library02.Mar2024.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings2016 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings2016() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rezultz.Library02.Mar2024.Strings.Strings2016", typeof(Strings2016).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code name furnished for data preprocessor not recognized..
        /// </summary>
        internal static string CodeNameFurnishedForConverterNotRecognzed {
            get {
                return ResourceManager.GetString("CodeNameFurnishedForConverterNotRecognzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-processing task complete..
        /// </summary>
        internal static string Complete__Conversion_process_ran_to_completion {
            get {
                return ResourceManager.GetString("Complete__Conversion_process_ran_to_completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation ran to completion. Gathering of metadata, data settings, and other data was driven by your metadataID..
        /// </summary>
        internal static string Download_of_metadata_and_datasettings_and_other_ran_to_completion {
            get {
                return ResourceManager.GetString("Download_of_metadata_and_datasettings_and_other_ran_to_completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. For one thing, there is no working dataset..
        /// </summary>
        internal static string ExplainIfIsNotReadyToProceedWithDataTransfer_Unable_to_proceed__For_one_thing__there_is_no_working_dataset_ {
            get {
                return ResourceManager.GetString("ExplainIfIsNotReadyToProceedWithDataTransfer_Unable_to_proceed__For_one_thing__th" +
                        "ere_is_no_working_dataset_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your target series points standings as :-.
        /// </summary>
        internal static string Export_your_target_series_points_standings_as___ {
            get {
                return ResourceManager.GetString("Export_your_target_series_points_standings_as___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your target series standings as :-.
        /// </summary>
        internal static string Export_your_target_series_standings_as___ {
            get {
                return ResourceManager.GetString("Export_your_target_series_standings_as___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your target series tour standings as :-.
        /// </summary>
        internal static string Export_your_target_series_tour_standings_as___ {
            get {
                return ResourceManager.GetString("Export_your_target_series_tour_standings_as___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure. Operation to pre-process data to comply with Rezultz input format ran into difficulty..
        /// </summary>
        internal static string Failure__Operation_to_convert_timing_tent_data_to_comply_with_Rezultz_input_format_ran_into_difficulty_ {
            get {
                return ResourceManager.GetString("Failure__Operation_to_convert_timing_tent_data_to_comply_with_Rezultz_input_forma" +
                        "t_ran_into_difficulty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to change your target, please do so before proceeding to initialise..
        /// </summary>
        internal static string If_you_wish_to_change_your_target__please_do_so_now {
            get {
                return ResourceManager.GetString("If_you_wish_to_change_your_target__please_do_so_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue an upload destination needs to be known. .
        /// </summary>
        internal static string In_order_to_continue__an_upload_destination_needs_to_be_known {
            get {
                return ResourceManager.GetString("In_order_to_continue__an_upload_destination_needs_to_be_known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue, please select a blob name.
        /// </summary>
        internal static string In_order_to_continue__please_select_a_blob_name {
            get {
                return ResourceManager.GetString("In_order_to_continue__please_select_a_blob_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue, please select a series.
        /// </summary>
        internal static string In_order_to_continue__please_select_a_series {
            get {
                return ResourceManager.GetString("In_order_to_continue__please_select_a_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue, please select an event.
        /// </summary>
        internal static string In_order_to_continue__please_select_an_event {
            get {
                return ResourceManager.GetString("In_order_to_continue__please_select_an_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete. Pre-processing task failed to run to completion.
        /// </summary>
        internal static string Incomplete__Conversion_process_failed_to_run_to_completion {
            get {
                return ResourceManager.GetString("Incomplete__Conversion_process_failed_to_run_to_completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet signed in..
        /// </summary>
        internal static string Not_yet_signed_in {
            get {
                return ResourceManager.GetString("Not_yet_signed_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation of results ran to completion..
        /// </summary>
        internal static string Operation_to_calculate_results_ran_to_completion {
            get {
                return ResourceManager.GetString("Operation_to_calculate_results_ran_to_completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-processing of data to comply with Rezultz input format ran to completion..
        /// </summary>
        internal static string Operation_to_convert_timing_tent_data_to_comply_with_Rezultz_input_format_ran_to_completion_ {
            get {
                return ResourceManager.GetString("Operation_to_convert_timing_tent_data_to_comply_with_Rezultz_input_format_ran_to_" +
                        "completion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download of data ran to completion..
        /// </summary>
        internal static string Operation_to_download_data_ran_to_completion {
            get {
                return ResourceManager.GetString("Operation_to_download_data_ran_to_completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload of pre-processed data ran to completion..
        /// </summary>
        internal static string Operation_to_upload_converted_data_to_production_storage_ran_to_completion_ {
            get {
                return ResourceManager.GetString("Operation_to_upload_converted_data_to_production_storage_ran_to_completion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload of pre-processed data to staging storage ran to completion..
        /// </summary>
        internal static string Operation_to_upload_data_to_preview_ran_to_completion_ {
            get {
                return ResourceManager.GetString("Operation_to_upload_data_to_preview_ran_to_completion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not recognised..
        /// </summary>
        internal static string Password_not_recognised_ {
            get {
                return ResourceManager.GetString("Password_not_recognised_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired column format for the table of results is unspecified or unrecognised. Sorry. Coding error..
        /// </summary>
        internal static string The_desired_column_format_for_the_table_of_results_is_unspecified_or_unrecognised__Sorry__Coding_error {
            get {
                return ResourceManager.GetString("The_desired_column_format_for_the_table_of_results_is_unspecified_or_unrecognised" +
                        "__Sorry__Coding_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialise profile and settings for obscure reasons. Do not proceed..
        /// </summary>
        internal static string Unable_to_initialise_RepositoryOfProfileAndSettingsForGroupOfSeries_for_obscure_reasons__Do_not_proceed {
            get {
                return ResourceManager.GetString("Unable_to_initialise_RepositoryOfProfileAndSettingsForGroupOfSeries_for_obscure_r" +
                        "easons__Do_not_proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. For one thing, the blob name for the intended data transfer has not yet been identified..
        /// </summary>
        internal static string Unable_to_proceed__For_one_thing__the_blobname_for_the_intended_data_transfer_has_not_yet_been_identified_1 {
            get {
                return ResourceManager.GetString("Unable_to_proceed__For_one_thing__the_blobname_for_the_intended_data_transfer_has" +
                        "_not_yet_been_identified_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. For one thing, the sporting event corresponding to the intended data transfer has not yet been identified..
        /// </summary>
        internal static string Unable_to_proceed__For_one_thing__the_event_corresponding_to_the_intended_data_transfer_has_not_yet_been_identified_ {
            get {
                return ResourceManager.GetString("Unable_to_proceed__For_one_thing__the_event_corresponding_to_the_intended_data_tr" +
                        "ansfer_has_not_yet_been_identified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. For one thing, the parent series of the sporting event corresponding to the intended data transfer has not yet been identified..
        /// </summary>
        internal static string Unable_to_proceed__For_one_thing__the_parent_series_of_the_event_corresponding_to_the_intended_data_transfer_has_not_yet_been_identified_ {
            get {
                return ResourceManager.GetString("Unable_to_proceed__For_one_thing__the_parent_series_of_the_event_corresponding_to" +
                        "_the_intended_data_transfer_has_not_yet_been_identified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. Unable to deduce a file name for this upload. Data error. The BlobName relating to this sporting event is null or white space..
        /// </summary>
        internal static string Unable_to_proceed__The_BlobName_relating_to_this_event_is_null_or_whitespace {
            get {
                return ResourceManager.GetString("Unable_to_proceed__The_BlobName_relating_to_this_event_is_null_or_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. We are unable to deduce a blob name for this upload.  The &lt;CurrentItem&gt; property of the current &lt;CboPreProcessedDataLocationForEventLookUpPresenter&gt; is null..
        /// </summary>
        internal static string Unable_to_proceed__Unable_to_deduce_a_blob_name_for_this_upload {
            get {
                return ResourceManager.GetString("Unable_to_proceed__Unable_to_deduce_a_blob_name_for_this_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. We are unable to deduce a destination for this upload. Coding error. Enumeration value not found..
        /// </summary>
        internal static string Unable_to_proceed__Unable_to_deduce_a_destination_for_upload {
            get {
                return ResourceManager.GetString("Unable_to_proceed__Unable_to_deduce_a_destination_for_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. We are unable to deduce a destination for this upload. Data error. The &lt;DatabaseForResultsPublished&gt; property of the current &lt;SeriesItem&gt; is null..
        /// </summary>
        internal static string Unable_to_proceed__Unable_to_deduce_a_destination_for_upload_to_production {
            get {
                return ResourceManager.GetString("Unable_to_proceed__Unable_to_deduce_a_destination_for_upload_to_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. We are unable to deduce a destination for this upload. Data error. The &lt;DocumentsPostedContainer&gt; property of the current &lt;SeriesItem&gt; is null..
        /// </summary>
        internal static string Unable_to_proceed__Unable_to_deduce_a_destination_for_upload_to_public {
            get {
                return ResourceManager.GetString("Unable_to_proceed__Unable_to_deduce_a_destination_for_upload_to_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. We are unable to deduce a destination for this upload. Data error. The &lt;DocumentsPostedContainer&gt; property of the current &lt;SeriesItem&gt; is null..
        /// </summary>
        internal static string Unable_to_proceed__Unable_to_deduce_a_destination_for_upload_to_staging {
            get {
                return ResourceManager.GetString("Unable_to_proceed__Unable_to_deduce_a_destination_for_upload_to_staging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. You need to authenticate yourself before proceeding..
        /// </summary>
        internal static string Unable_to_proceed__You_need_to_authenticate_yourself_before_proceeding_ {
            get {
                return ResourceManager.GetString("Unable_to_proceed__You_need_to_authenticate_yourself_before_proceeding_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. Your input file is empty. It contains nothing..
        /// </summary>
        internal static string Unable_to_proceed__Your_input_file_is_empty__It_contains_nothing_ {
            get {
                return ResourceManager.GetString("Unable_to_proceed__Your_input_file_is_empty__It_contains_nothing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. The format of your metadataID is invalid. .
        /// </summary>
        internal static string Unable_to_proceed_For_one_thing_the_metadataID_is_invalid {
            get {
                return ResourceManager.GetString("Unable_to_proceed_For_one_thing_the_metadataID_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not recognised..
        /// </summary>
        internal static string UserName_not_recognised_ {
            get {
                return ResourceManager.GetString("UserName_not_recognised_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... computing_series_standings.
        /// </summary>
        internal static string Working______computing_series_standings {
            get {
                return ResourceManager.GetString("Working______computing_series_standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... doing preprocessing on server.
        /// </summary>
        internal static string Working______doing_preprocessing_on_server {
            get {
                return ResourceManager.GetString("Working______doing_preprocessing_on_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... posting leaderboard for single event as HTML document.
        /// </summary>
        internal static string Working______posting_leaderboard_for_single_event_as_HTML_document {
            get {
                return ResourceManager.GetString("Working______posting_leaderboard_for_single_event_as_HTML_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... posting series points standings.
        /// </summary>
        internal static string Working______posting_series_points_standings {
            get {
                return ResourceManager.GetString("Working______posting_series_points_standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... posting series tour standings.
        /// </summary>
        internal static string Working______posting_series_tour_standings {
            get {
                return ResourceManager.GetString("Working______posting_series_tour_standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... pulling participant profiles from rezultz hub.
        /// </summary>
        internal static string Working______pulling_participant_profiles_from_rezultz_hub {
            get {
                return ResourceManager.GetString("Working______pulling_participant_profiles_from_rezultz_hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... pulling timestamps from rezultz hub.
        /// </summary>
        internal static string Working______pulling_timestamps_from_rezultz_hub {
            get {
                return ResourceManager.GetString("Working______pulling_timestamps_from_rezultz_hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... uploading.
        /// </summary>
        internal static string Working______uploading {
            get {
                return ResourceManager.GetString("Working______uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... calculating.
        /// </summary>
        internal static string Working_____calculating {
            get {
                return ResourceManager.GetString("Working_____calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... computing leaderboard for single event.
        /// </summary>
        internal static string Working_____computing_leaderboard_for_single_event {
            get {
                return ResourceManager.GetString("Working_____computing_leaderboard_for_single_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... preprocessing.
        /// </summary>
        internal static string Working_____converting {
            get {
                return ResourceManager.GetString("Working_____converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... downloading.
        /// </summary>
        internal static string Working_____downloading {
            get {
                return ResourceManager.GetString("Working_____downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... downloading results for multiple events in series.
        /// </summary>
        internal static string Working_____downloading__results_for_multiple_events_in_series {
            get {
                return ResourceManager.GetString("Working_____downloading__results_for_multiple_events_in_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... downloading pre-processed data, calculating race results and uploading web documents.
        /// </summary>
        internal static string Working_____downloading_preprocessed_data_calculating_race_results_publishing_web_pages {
            get {
                return ResourceManager.GetString("Working_____downloading_preprocessed_data_calculating_race_results_publishing_web" +
                        "_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... downloading results for single event.
        /// </summary>
        internal static string Working_____downloading_results_for_single_event {
            get {
                return ResourceManager.GetString("Working_____downloading_results_for_single_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... validating.
        /// </summary>
        internal static string Working____validating {
            get {
                return ResourceManager.GetString("Working____validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to authenticate yourself before proceeding..
        /// </summary>
        internal static string You_need_to_authenticate_yourself_before_proceeding_ {
            get {
                return ResourceManager.GetString("You_need_to_authenticate_yourself_before_proceeding_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to launch the app to start work..
        /// </summary>
        internal static string You_need_to_launch_the_app_to_start_work_ {
            get {
                return ResourceManager.GetString("You_need_to_launch_the_app_to_start_work_", resourceCulture);
            }
        }
    }
}
