//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultz.Library02.Mar2024.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings2017 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings2017() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rezultz.Library02.Mar2024.Strings.Strings2017", typeof(Strings2017).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age group.
        /// </summary>
        internal static string AgeGroup_ {
            get {
                return ResourceManager.GetString("AgeGroup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City_ {
            get {
                return ResourceManager.GetString("City_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification data not found.
        /// </summary>
        internal static string Classification_data_not_found {
            get {
                return ResourceManager.GetString("Classification_data_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock mode.
        /// </summary>
        internal static string Clock_mode {
            get {
                return ResourceManager.GetString("Clock_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data error. Enum converterCode for type of event statistics not recognised. There is a problem in the metadata. There is a mismatch between what&apos;s in the metadata and what the cohortCode is written to handle..
        /// </summary>
        internal static string Data_error__event_stats_enum_not_recognised {
            get {
                return ResourceManager.GetString("Data_error__event_stats_enum_not_recognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days to go. Advertised for {1}.
        /// </summary>
        internal static string Days_to_go__Advertised_for {
            get {
                return ResourceManager.GetString("Days_to_go__Advertised_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnf status.
        /// </summary>
        internal static string Dnx_status {
            get {
                return ResourceManager.GetString("Dnx_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string Filters_ {
            get {
                return ResourceManager.GetString("Filters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender_ {
            get {
                return ResourceManager.GetString("Gender_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show favorites.
        /// </summary>
        internal static string Header_Favorites_List {
            get {
                return ResourceManager.GetString("Header_Favorites_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours to go. Advertised for {1}.
        /// </summary>
        internal static string hours_to_go__Advertised_for {
            get {
                return ResourceManager.GetString("hours_to_go__Advertised_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of events is empty.  One or more events are required..
        /// </summary>
        internal static string List_of_events_is_empty {
            get {
                return ResourceManager.GetString("List_of_events_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of series is empty.  One or more series are required..
        /// </summary>
        internal static string List_of_series_is_empty {
            get {
                return ResourceManager.GetString("List_of_series_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata not initialised.
        /// </summary>
        internal static string Metadata_and_datasettings_not_initialised {
            get {
                return ResourceManager.GetString("Metadata_and_datasettings_not_initialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata not loaded..
        /// </summary>
        internal static string MetadataNotLoaded {
            get {
                return ResourceManager.GetString("MetadataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes to go. Advertised for {1}.
        /// </summary>
        internal static string Minutes_to_go__advertised_for_ {
            get {
                return ResourceManager.GetString("Minutes_to_go__advertised_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information not selected..
        /// </summary>
        internal static string More_information_not_selected {
            get {
                return ResourceManager.GetString("More_information_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found in this subset.
        /// </summary>
        internal static string No_items_found_in_this_subset {
            get {
                return ResourceManager.GetString("No_items_found_in_this_subset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string Not_found {
            get {
                return ResourceManager.GetString("Not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other__ {
            get {
                return ResourceManager.GetString("Other__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohorts.
        /// </summary>
        internal static string Other_cohorts {
            get {
                return ResourceManager.GetString("Other_cohorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other events.
        /// </summary>
        internal static string Other_events {
            get {
                return ResourceManager.GetString("Other_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        internal static string Other_leaderboards {
            get {
                return ResourceManager.GetString("Other_leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other series.
        /// </summary>
        internal static string Other_seasons {
            get {
                return ResourceManager.GetString("Other_seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other standings.
        /// </summary>
        internal static string Other_standings {
            get {
                return ResourceManager.GetString("Other_standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid metadataID must be entered..
        /// </summary>
        internal static string Please_check_your_metadataID {
            get {
                return ResourceManager.GetString("Please_check_your_metadataID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting complete..
        /// </summary>
        internal static string Posting_of_document_ran_to_completion_ {
            get {
                return ResourceManager.GetString("Posting_of_document_ran_to_completion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Race__ {
            get {
                return ResourceManager.GetString("Race__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results__ {
            get {
                return ResourceManager.GetString("Results__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results not found.
        /// </summary>
        internal static string Results_not_found {
            get {
                return ResourceManager.GetString("Results_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select name of blob to be uploaded.
        /// </summary>
        internal static string Select_blob {
            get {
                return ResourceManager.GetString("Select_blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. Unable to proceed. Your  authorisation does not include clearance to work with the current metadataID..
        /// </summary>
        internal static string Sorry_not_authorised_for_metadataId {
            get {
                return ResourceManager.GetString("Sorry_not_authorised_for_metadataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. Unable to proceed. Your  authorisation does not include clearance in a work role that allows you to post data..
        /// </summary>
        internal static string Sorry_not_authorised_for_workrole {
            get {
                return ResourceManager.GetString("Sorry_not_authorised_for_workrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of series points standings not found..
        /// </summary>
        internal static string Table_of_points_standings_not_found {
            get {
                return ResourceManager.GetString("Table_of_points_standings_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of series tour leaders not found..
        /// </summary>
        internal static string Table_of_tour_duration_standings_not_found {
            get {
                return ResourceManager.GetString("Table_of_tour_duration_standings_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team__ {
            get {
                return ResourceManager.GetString("Team__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete computations and calculations to load page..
        /// </summary>
        internal static string Unable_to_complete_computations_and_calculations_to_load_page_ {
            get {
                return ResourceManager.GetString("Unable_to_complete_computations_and_calculations_to_load_page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify if the current metadataID is valid..
        /// </summary>
        internal static string Unable_to_establish_if_current_metadataID_is_valid {
            get {
                return ResourceManager.GetString("Unable_to_establish_if_current_metadataID_is_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the data associated with this metadataID..
        /// </summary>
        internal static string Unable_to_find_metadata_for_current_metadataID {
            get {
                return ResourceManager.GetString("Unable_to_find_metadata_for_current_metadataID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of participants is not currently loaded so it is premature to determine if this is a valid race number. The category of participants containing the target bib number will be featured if and when the target materialises..
        /// </summary>
        internal static string Unable_to_investigate_bib_number__participants_not_yet_loaded_ {
            get {
                return ResourceManager.GetString("Unable_to_investigate_bib_number__participants_not_yet_loaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load metadata..
        /// </summary>
        internal static string Unable_to_load_repository_of_metadata_and_datasettings_ {
            get {
                return ResourceManager.GetString("Unable_to_load_repository_of_metadata_and_datasettings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding error. Unable to retrieve instance of interface or object from dependency injection container. Item is not registered..
        /// </summary>
        internal static string Unable_to_retrieve_instance {
            get {
                return ResourceManager.GetString("Unable_to_retrieve_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome__ {
            get {
                return ResourceManager.GetString("Welcome__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... abandoning modification.
        /// </summary>
        internal static string Working_____abandoning_modification {
            get {
                return ResourceManager.GetString("Working_____abandoning_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... adding displayObject to cache.
        /// </summary>
        internal static string Working_____adding_item_to_cache {
            get {
                return ResourceManager.GetString("Working_____adding_item_to_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... adding new displayObject.
        /// </summary>
        internal static string Working_____adding_stopwatch_data_item {
            get {
                return ResourceManager.GetString("Working_____adding_stopwatch_data_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... authenticating.
        /// </summary>
        internal static string Working_____authenticating {
            get {
                return ResourceManager.GetString("Working_____authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... checking in.
        /// </summary>
        internal static string Working_____checking_in {
            get {
                return ResourceManager.GetString("Working_____checking_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... committing data to storage.
        /// </summary>
        internal static string Working_____committing_data {
            get {
                return ResourceManager.GetString("Working_____committing_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... deleting all data.
        /// </summary>
        internal static string Working_____deleting_all_data {
            get {
                return ResourceManager.GetString("Working_____deleting_all_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... deleting displayObject.
        /// </summary>
        internal static string Working_____deleting_item {
            get {
                return ResourceManager.GetString("Working_____deleting_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... formatting.
        /// </summary>
        internal static string Working_____formatting {
            get {
                return ResourceManager.GetString("Working_____formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... launching modification.
        /// </summary>
        internal static string Working_____launching_modfication {
            get {
                return ResourceManager.GetString("Working_____launching_modfication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... loading data from local storage.
        /// </summary>
        internal static string Working_____loading_data_from_local_storage {
            get {
                return ResourceManager.GetString("Working_____loading_data_from_local_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... looking for information.
        /// </summary>
        internal static string Working_____looking_for_information {
            get {
                return ResourceManager.GetString("Working_____looking_for_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working .... post-processing.
        /// </summary>
        internal static string Working_____processing {
            get {
                return ResourceManager.GetString("Working_____processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... pulling data from hub.
        /// </summary>
        internal static string Working_____pulling_data_from_hub {
            get {
                return ResourceManager.GetString("Working_____pulling_data_from_hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... pushing data to hub.
        /// </summary>
        internal static string Working_____pushing_data_to_hub {
            get {
                return ResourceManager.GetString("Working_____pushing_data_to_hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... submitting profile.
        /// </summary>
        internal static string Working_____submitting_profile {
            get {
                return ResourceManager.GetString("Working_____submitting_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ... verifying profile.
        /// </summary>
        internal static string Working_____verifying_profile {
            get {
                return ResourceManager.GetString("Working_____verifying_profile", resourceCulture);
            }
        }
    }
}
