//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHarnessConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
    [System.SerializableAttribute()]
    public partial class JghFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NarrativeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Narrative {
            get {
                return this.NarrativeField;
            }
            set {
                if ((object.ReferenceEquals(this.NarrativeField, value) != true)) {
                    this.NarrativeField = value;
                    this.RaisePropertyChanged("Narrative");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITimingSystemDataPreprocessingSvc")]
    public interface ITimingSystemDataPreprocessingSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetIfServiceIsAnswering", ReplyAction="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetIfServiceIsAnsweringRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestHarnessConsole.ServiceReference1.JghFault), Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetIfServiceIsAnsweringJghFa" +
            "ultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
        bool GetIfServiceIsAnswering();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetServiceEndpointsInfo", ReplyAction="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetServiceEndpointsInfoRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestHarnessConsole.ServiceReference1.JghFault), Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetServiceEndpointsInfoJghFa" +
            "ultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
        string[] GetServiceEndpointsInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetListOfPreprocessors", ReplyAction="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetListOfPreprocessorsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestHarnessConsole.ServiceReference1.JghFault), Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetListOfPreprocessorsJghFau" +
            "ltFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
        string GetListOfPreprocessors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetIfPreprocessorIdIsRecogni" +
            "sed", ReplyAction="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetIfPreprocessorIdIsRecogni" +
            "sedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestHarnessConsole.ServiceReference1.JghFault), Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetIfPreprocessorIdIsRecogni" +
            "sedJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
        bool GetIfPreprocessorIdIsRecognised(string preprocessorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetInfoAboutPreprocessor", ReplyAction="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetInfoAboutPreprocessorResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestHarnessConsole.ServiceReference1.JghFault), Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetInfoAboutPreprocessorJghF" +
            "aultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
        string GetInfoAboutPreprocessor(string preprocessorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetInstructionsFromPreproces" +
            "sor", ReplyAction="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetInstructionsFromPreproces" +
            "sorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestHarnessConsole.ServiceReference1.JghFault), Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/GetInstructionsFromPreproces" +
            "sorJghFaultFault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
        string GetInstructionsFromPreprocessor(string preprocessorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/PreprocessTimingData", ReplyAction="http://tempuri.org/ITimingSystemDataPreprocessingSvc/PreprocessTimingDataResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestHarnessConsole.ServiceReference1.JghFault), Action="http://tempuri.org/ITimingSystemDataPreprocessingSvc/PreprocessTimingDataJghFault" +
            "Fault", Name="JghFault", Namespace="http://schemas.datacontract.org/2004/07/RezultzSvc.CoreWcf._11.May2023")]
        byte[] PreprocessTimingData(string preprocessorId, byte[] preprocessorPayloadAsJsonAsCompressedBytes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimingSystemDataPreprocessingSvcChannel : TestHarnessConsole.ServiceReference1.ITimingSystemDataPreprocessingSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimingSystemDataPreprocessingSvcClient : System.ServiceModel.ClientBase<TestHarnessConsole.ServiceReference1.ITimingSystemDataPreprocessingSvc>, TestHarnessConsole.ServiceReference1.ITimingSystemDataPreprocessingSvc {
        
        public TimingSystemDataPreprocessingSvcClient() {
        }
        
        public TimingSystemDataPreprocessingSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimingSystemDataPreprocessingSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimingSystemDataPreprocessingSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimingSystemDataPreprocessingSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetIfServiceIsAnswering() {
            return base.Channel.GetIfServiceIsAnswering();
        }
        
        public string[] GetServiceEndpointsInfo() {
            return base.Channel.GetServiceEndpointsInfo();
        }
        
        public string GetListOfPreprocessors() {
            return base.Channel.GetListOfPreprocessors();
        }
        
        public bool GetIfPreprocessorIdIsRecognised(string preprocessorId) {
            return base.Channel.GetIfPreprocessorIdIsRecognised(preprocessorId);
        }
        
        public string GetInfoAboutPreprocessor(string preprocessorId) {
            return base.Channel.GetInfoAboutPreprocessor(preprocessorId);
        }
        
        public string GetInstructionsFromPreprocessor(string preprocessorId) {
            return base.Channel.GetInstructionsFromPreprocessor(preprocessorId);
        }
        
        public byte[] PreprocessTimingData(string preprocessorId, byte[] preprocessorPayloadAsJsonAsCompressedBytes) {
            return base.Channel.PreprocessTimingData(preprocessorId, preprocessorPayloadAsJsonAsCompressedBytes);
        }
    }
}
